version: '3.7'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nechba
      - MYSQL_DATABASE=blanate
    ports:
      - "3306:3306"
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

  blane:
    image: kamalessafi/blane-kubernetes:0.0.11-SNAPSHOT
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "8000:8000"
    environment:
      RDS_HOSTNAME: mysqldb
      RDS_PORT: 3306
      RDS_DB_NAME: blanate
      RDS_USERNAME: root
      RDS_PASSWORD: nechba


  blane-additional-services:
    image: kamalessafi/blane-additional-services-kubernetes:0.0.11-SNAPSHOT
    restart: always
    depends_on:
      - mysqldb
      - blane
    ports:
      - "8200:8200"
    environment:
      RDS_HOSTNAME: mysqldb
      RDS_PORT: 3306
      RDS_DB_NAME: blanate
      RDS_USERNAME: root
      RDS_PASSWORD: nechba


  blane-scheduler:
    image: kamalessafi/blane-scheduler-kubernetes:0.0.11-SNAPSHOT
    restart: always
    depends_on:
      - mysqldb
      - blane
    environment:
      RDS_HOSTNAME: mysqldb
      RDS_PORT: 3306
      RDS_DB_NAME: blanate
      RDS_USERNAME: root
      RDS_PASSWORD: nechba

      # Volumes
volumes:
  mysql-database-data-volume:

